'use strict';

/**
 * store.js — Cross-project memory store.
 *
 * Factory function that creates a memory store backed by JSON files
 * in ~/.team-sdk/memory/. Provides ingest, query, and stats operations.
 */

const { readFileSync, writeFileSync, mkdirSync, existsSync } = require('fs');
const path = require('path');
const { ingestProject } = require('./ingest');
const { validateEntry, normalizeEntry, entryId } = require('./schema');
const { queryEntries, getDecisions, getKills, getChallenges, corpusStats, filterEntries } = require('./query');

const DEFAULT_STORE_DIR = path.join(
  process.env.HOME || process.env.USERPROFILE || '~',
  '.team-sdk', 'memory'
);

/**
 * Create a memory store instance.
 *
 * @param {object} [config]
 * @param {string} [config.storeDir] — Directory for JSON files (default: ~/.team-sdk/memory/)
 * @returns {object} Memory store interface
 */
function createMemoryStore(config = {}) {
  const storeDir = config.storeDir || DEFAULT_STORE_DIR;

  // Ensure directory exists
  mkdirSync(storeDir, { recursive: true });

  const paths = {
    decisions: path.join(storeDir, 'decisions.json'),
    kills: path.join(storeDir, 'kill-log.json'),
    challenges: path.join(storeDir, 'challenges.json'),
    index: path.join(storeDir, 'index.json'),
    killMd: path.join(storeDir, 'kill-log.md'),
  };

  // --- Persistence ---

  function loadFile(filePath) {
    if (!existsSync(filePath)) return [];
    try {
      return JSON.parse(readFileSync(filePath, 'utf8'));
    } catch {
      return [];
    }
  }

  function saveFile(filePath, data) {
    writeFileSync(filePath, JSON.stringify(data, null, 2));
  }

  function loadAll() {
    return [
      ...loadFile(paths.decisions),
      ...loadFile(paths.kills),
      ...loadFile(paths.challenges),
    ];
  }

  function saveByType(entries) {
    const decisions = entries.filter(e => e.type === 'decision');
    const kills = entries.filter(e => e.type === 'kill');
    const challenges = entries.filter(e => e.type === 'challenge');

    saveFile(paths.decisions, decisions);
    saveFile(paths.kills, kills);
    saveFile(paths.challenges, challenges);

    // Update kill-log.md (human-readable mirror)
    if (kills.length > 0) {
      const md = renderKillLogMd(kills);
      writeFileSync(paths.killMd, md);
    }

    // Update index
    updateIndex(entries);
  }

  function updateIndex(entries) {
    const projects = {};
    for (const e of entries) {
      if (!projects[e.project]) {
        projects[e.project] = {
          name: e.project,
          projectDir: e.projectDir || null,
          entryCount: 0,
          lastIngest: null,
        };
      }
      projects[e.project].entryCount++;
      if (!projects[e.project].lastIngest || e.ingestedAt > projects[e.project].lastIngest) {
        projects[e.project].lastIngest = e.ingestedAt;
      }
    }

    const index = {
      version: '1.0',
      updatedAt: new Date().toISOString(),
      totalEntries: entries.length,
      projects,
    };
    saveFile(paths.index, index);
  }

  function renderKillLogMd(kills) {
    const lines = [
      '# Kill Log — Cross-Project Judgment Corpus',
      '',
      '> Auto-generated by @team-sdk/memory. Do not edit manually.',
      '',
      '| Date | Project | Class | Summary |',
      '|---|---|---|---|',
    ];
    for (const k of kills.sort((a, b) => (b.date || '').localeCompare(a.date || ''))) {
      lines.push(`| ${k.date} | ${k.project} | ${k.killClass || '-'} | ${(k.summary || '').slice(0, 80)} |`);
    }
    lines.push('');
    return lines.join('\n');
  }

  // --- Public API ---

  return {
    /**
     * Ingest all entries from a project directory.
     * Idempotent: entries with the same ID are deduplicated.
     * @returns {{ added: number, skipped: number, total: number }}
     */
    ingest(projectDir) {
      const newEntries = ingestProject(projectDir);
      const existing = loadAll();
      const existingIds = new Set(existing.map(e => e.id));

      let added = 0;
      let skipped = 0;

      for (const entry of newEntries) {
        const errors = validateEntry(entry);
        if (errors.length > 0) {
          skipped++;
          continue;
        }
        if (existingIds.has(entry.id)) {
          skipped++;
          continue;
        }
        existing.push(entry);
        existingIds.add(entry.id);
        added++;
      }

      saveByType(existing);
      return { added, skipped, total: existing.length };
    },

    /**
     * Ingest a single kill entry (called by sdk-kill).
     */
    ingestKill(killEntry) {
      const entry = normalizeEntry({
        type: 'kill',
        ...killEntry,
      });
      const errors = validateEntry(entry);
      if (errors.length > 0) return { added: 0, errors };

      const existing = loadAll();
      if (existing.some(e => e.id === entry.id)) {
        return { added: 0, duplicate: true };
      }

      existing.push(entry);
      saveByType(existing);
      return { added: 1 };
    },

    /**
     * Query the corpus by keyword.
     */
    query(question, options = {}) {
      return queryEntries(loadAll(), question, options);
    },

    /**
     * List all projects that have contributed entries.
     */
    listProjects() {
      const indexPath = paths.index;
      if (!existsSync(indexPath)) return [];
      try {
        const index = JSON.parse(readFileSync(indexPath, 'utf8'));
        return Object.values(index.projects || {});
      } catch {
        return [];
      }
    },

    /**
     * Get decisions with optional filters.
     */
    getDecisions(filters) {
      return getDecisions(loadAll(), filters);
    },

    /**
     * Get kills with optional filters.
     */
    getKills(filters) {
      return getKills(loadAll(), filters);
    },

    /**
     * Get challenges with optional filters.
     */
    getChallenges(filters) {
      return getChallenges(loadAll(), filters);
    },

    /**
     * Corpus statistics.
     */
    stats() {
      return corpusStats(loadAll());
    },

    /**
     * Get the store directory path.
     */
    getStoreDir() {
      return storeDir;
    },
  };
}

module.exports = { createMemoryStore, DEFAULT_STORE_DIR };
